/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AgentContextRouteImport } from './routes/agent-context'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayIntentIdRouteImport } from './routes/pay.$intentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentContextRoute = AgentContextRouteImport.update({
  id: '/agent-context',
  path: '/agent-context',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIntentIdRoute = PayIntentIdRouteImport.update({
  id: '/pay/$intentId',
  path: '/pay/$intentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-context': typeof AgentContextRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-context': typeof AgentContextRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-context': typeof AgentContextRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-context'
    | '/docs'
    | '/history'
    | '/settings'
    | '/pay/$intentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-context'
    | '/docs'
    | '/history'
    | '/settings'
    | '/pay/$intentId'
  id:
    | '__root__'
    | '/'
    | '/agent-context'
    | '/docs'
    | '/history'
    | '/settings'
    | '/pay/$intentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentContextRoute: typeof AgentContextRoute
  DocsRoute: typeof DocsRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  PayIntentIdRoute: typeof PayIntentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-context': {
      id: '/agent-context'
      path: '/agent-context'
      fullPath: '/agent-context'
      preLoaderRoute: typeof AgentContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$intentId': {
      id: '/pay/$intentId'
      path: '/pay/$intentId'
      fullPath: '/pay/$intentId'
      preLoaderRoute: typeof PayIntentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentContextRoute: AgentContextRoute,
  DocsRoute: DocsRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  PayIntentIdRoute: PayIntentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
